Chris course selection screen001
dellydel/student-tracker pull request #24
Opened 2023-09-03 21:20 UTC by BorisLaboratory

Chris course selection screen001

2023-09-04 04:16 UTC, dellydel requested changes

2023-09-04 04:16 UTC, dellydel commented on front-end/src/components/courseList.json
I would set up a new folder to store all the test data in. Create a new test-data folder at the root level of the application, instead of including it in the components folder.

2023-09-05 06:05 UTC, BorisLaboratory commented on front-end/src/components/courseList.json
test-data folder created

2023-09-05 17:46 UTC, dellydel approved these changes

2023-09-05 21:37 UTC, merged