ChrisCourseDetail001
dellydel/student-tracker pull request #25
Opened 2023-09-03 22:20 UTC by BorisLaboratory

Added CourseDetail functionality

2023-09-04 04:10 UTC, dellydel requested changes

2023-09-04 04:10 UTC, dellydel commented on front-end/src/components/CourseDetail.js
> +const CSS = ({
Component name should match file name

2023-09-05 06:20 UTC, BorisLaboratory commented on front-end/src/components/CourseDetail.js
> +const CSS = ({
resolved

2023-09-05 17:47 UTC, dellydel approved these changes

2023-09-06 01:52 UTC, dellydel approved these changes

2023-09-06 06:21 UTC, merged